"""OCR機能を提供するモジュール（後方互換 re-export レイヤー）。"""

from ._engine import (
    _ALLOWED_TESSERACT_FLAGS,
    _AVERAGE_CONFIDENCE_THRESHOLD,
    _EARLY_STOP_CONFIDENCE,
    _OCR_BASE_CONFIG,
    _OCR_PSM_CANDIDATES,
    _SHELL_META_CHARS,
    _TEXT_RENDER_CONFIDENCE_THRESHOLD,
    _UPSCALE_FACTOR,
    AdaptiveOCRResult,
    _build_tesseract_configs,
    _compute_average_confidence,
    _filter_frame_by_confidence,
    _image_to_data,
    _perform_adaptive_ocr,
    _prepare_frame,
    _preprocess_for_ocr,
    _run_ocr_with_best_config,
    _sanitize_tesseract_config,
)
from ._environment import (
    _FONT_PATH_CACHE,
    _candidate_font_directories,
    _find_japanese_font_path,
    _try_assign_candidates,
    _validate_tesseract_setting,
    find_and_set_tesseract_path,
)
from ._exceptions import OCRCancelledError, OCRConversionError, PDFPasswordRemovalError
from ._pdf import (
    _determine_canvas_size,
    _normalize_image_for_canvas,
    create_searchable_pdf,
    create_searchable_pdf_from_images,
    extract_text_from_image_pdf,
    extract_text_to_file,
    remove_pdf_password,
)
from ._utils import (
    _build_progress_message,
    _extract_coordinates,
    _format_duration,
    _prepare_output_path,
)

__all__ = [
    "_ALLOWED_TESSERACT_FLAGS",
    "_AVERAGE_CONFIDENCE_THRESHOLD",
    "_EARLY_STOP_CONFIDENCE",
    "_FONT_PATH_CACHE",
    "_OCR_BASE_CONFIG",
    "_OCR_PSM_CANDIDATES",
    "_SHELL_META_CHARS",
    "_TEXT_RENDER_CONFIDENCE_THRESHOLD",
    "_UPSCALE_FACTOR",
    "AdaptiveOCRResult",
    "OCRCancelledError",
    "OCRConversionError",
    "PDFPasswordRemovalError",
    "_build_progress_message",
    "_build_tesseract_configs",
    "_candidate_font_directories",
    "_compute_average_confidence",
    "_determine_canvas_size",
    "_extract_coordinates",
    "_filter_frame_by_confidence",
    "_find_japanese_font_path",
    "_format_duration",
    "_image_to_data",
    "_normalize_image_for_canvas",
    "_perform_adaptive_ocr",
    "_prepare_frame",
    "_prepare_output_path",
    "_preprocess_for_ocr",
    "_run_ocr_with_best_config",
    "_sanitize_tesseract_config",
    "_try_assign_candidates",
    "_validate_tesseract_setting",
    "create_searchable_pdf",
    "create_searchable_pdf_from_images",
    "extract_text_from_image_pdf",
    "extract_text_to_file",
    "find_and_set_tesseract_path",
    "remove_pdf_password",
]
